### PR TITLE
feat: 512mb alignment

### PR DESCRIPTION
**Pull request by nothingneko**
For RPi imager

### CODE REVIEW

**Review by lleyton — APPROVED** [review]

**Comment by lleyton** [comment]
wait

**Review by lleyton — CHANGES_REQUESTED** [review]
do it for x86 and plain base too, basically any disk image (chromebook too?)

**Comment by nothingneko** [comment]
why?

**Review by lleyton — CHANGES_REQUESTED** [review]
plain base images, chromebook too?

**Comment by nothingneko** [comment]
i already made the changes to base proper and explained chromebook in voice, what's still wrong?

**Review by lleyton — APPROVED** [review]

**Pull request merged**
