### PR TITLE
Cleanup of confs and addition of ports infrastructure

### PR DESCRIPTION
**Pull request by nothingneko**

### CODE REVIEW

**Comment by nothingneko** [comment]
Do not merge

**Comment by lleyton** [comment]
arm is broken somehow

**Comment by lleyton** [comment]
image
I thought XFCE looked different (icon wise at least) may be tripping though

**Comment by nothingneko** [comment]
looks like it's using adw icons there what the fuck

**Comment by lleyton** [comment]
can you look into that?

**Review by lleyton — APPROVED** [review]

**Pull request merged**
